version: '2'

networks:
  domotic:

services:
  openhab:
    image: openhab/openhab:2.4.0-armhf-debian
    restart: always
    depends_on:
      - mariadb
    networks:
      domotic:
        aliases:
          - openhab
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab2/addons:/openhab/addons
      - ./openhab2/conf:/openhab/conf
      - ./openhab2/userdata:/openhab/userdata
      - /var/log/container-logs/:/openhab/userdata/logs
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Dos.arch=arm -Dsun.arch.abi=gnueabihf
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

  mariadb:
    image: jsurf/rpi-mariadb
    restart: always
    networks:
      domotic:
        aliases:
          - mariadb
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswordhere
      - MYSQL_DATABASE=openhab
      - MYSQL_USER=openhabuser
      - MYSQL_PASSWORD=openhabpass 
